Don't need /opt/VirtualGL/lib unless using TurboJPEG; Make uninstall script compatible with Snow Leopard, which no longer uses package receipts
git-svn-id: svn+ssh://svn.code.sf.net/p/virtualgl/code/trunk@2682 799e4f7b-5fd2-41f6-823c-2ecc41bc7f0b

diff --git a/uninstall.sh.tmpl b/uninstall.sh.tmpl
--- a/uninstall.sh.tmpl
+++ b/uninstall.sh.tmpl
@@ -1,4 +1,5 @@
 # Copyright (C)2009 Sun Microsystems, Inc.
+# Copyright (C)2009 D. R. Commander
 #
 # This library is free software and may be redistributed and/or modified under
 # the terms of the wxWindows Library License, Version 3.1 or (at your option)
@@ -23,29 +24,42 @@ if [ ! "`id -u`" = "0" ]; then
 fi
 
 PKGNAME={__APPNAME}
+MACPKGNAME=com.virtualgl.vglclient
 RCPT=/Library/Receipts/$PKGNAME.pkg
 
-if [ ! -d $RCPT ]; then error "Could not find package receipt"; fi
+LSBOM=
+if [ -d $RCPT ]; then
+	LSBOM='lsbom -s -f -l '$RCPT'/Contents/Archive.bom'
+else
+	LSBOM='pkgutil --files '$MACPKGNAME
+fi
 
 echo Removing files ...
-lsbom -s -f -l $RCPT/Contents/Archive.bom >/dev/null || error "Could not list package contents"
+$LSBOM >/dev/null || error "Could not list package contents"
 RETCODE=0
 PWD=`pwd`
 cd /
-lsbom -s -f -l $RCPT/Contents/Archive.bom | while read line; do
-	rm "$line" 2>&1 || RETCODE=-1
+$LSBOM | while read line; do
+	if [ ! -d "$line" ]; then rm "$line" 2>&1 || RETCODE=-1; fi
 done
 cd $PWD
 
 echo Removing directories ...
 rmdir /opt/VirtualGL/bin 2>&1 || RETCODE=-1
-rmdir /opt/VirtualGL/lib 2>&1 || RETCODE=-1
+if [ -d /opt/VirtualGL/lib ]; then
+	rmdir /opt/VirtualGL/lib 2>&1 || RETCODE=-1
+fi
 rmdir /opt/VirtualGL 2>&1 || RETCODE=-1
 rmdir /Library/Documentation/$PKGNAME 2>&1 || RETCODE=-1
 rmdir /Applications/VirtualGL 2>&1 || RETCODE=-1
 
-echo Removing package receipt $RCPT ...
-rm -r $RCPT 2>&1 || RETCODE=-1
+if [ -d $RCPT ]; then
+	echo Removing package receipt $RCPT ...
+	rm -r $RCPT 2>&1 || RETCODE=-1
+else
+	echo Forgetting package $MACPKGNAME
+	pkgutil --forget $MACPKGNAME
+fi
 
 for RCPT in /Library/Receipts/$PKGNAME-*.pkg; do
 	if [ -d $RCPT ]; then
