Faker: Access GPU w/o a 3D X server (EGL back end)
Refer to #10 for discussion.

Things that work:
- fakerut -nocopycontext
  (tested with helgrind and valgrind as well)
- all demos in glxdemos/ except texture_from_pixmap

Things that don't work yet but probably need to work before the final
release:
- glXCopyContext()
- GLX_EXT_texture_from_pixmap

Things that won't work:
- OpenCL/OpenGL interoperability (until nVidia implements
  CL_EGL_DISPLAY_KHR)

Possible future expansion:
- GLX_ARB_create_context_robustness
- GLX_ARB_fbconfig_float
- GLX_EXT_create_context_es2_profile
- GLX_EXT_framebuffer_sRGB

To do:
- Testing with real 3D applications
- Documentation

diff --git a/server/vglserver_config b/server/vglserver_config
--- a/server/vglserver_config
+++ b/server/vglserver_config
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Copyright (C)2007 Sun Microsystems, Inc.
-# Copyright (C)2009-2014, 2016, 2018-2019 D. R. Commander
+# Copyright (C)2009-2014, 2016, 2018-2020 D. R. Commander
 #
 # This library is free software and may be redistributed and/or modified under
 # the terms of the wxWindows Library License, Version 3.1 or (at your option)
@@ -20,6 +20,7 @@ RMMODNEEDED=0
 UNATTENDED=0
 SELINUX=0
 WAYLAND=0
+BACKEND=glx
 
 GID=
 GROUPADD=/usr/sbin/groupadd
@@ -42,8 +43,10 @@ usage()
 	echo "USAGE: $0 [flags]"
 	echo
 	echo "Flags (for unattended mode):"
-	echo "-config         Configure server for use with VirtualGL"
-	echo "-unconfig       Unconfigure server for use with VirtualGL"
+	echo "+glx/-config    Configure server for use with VirtualGL (GLX + EGL back ends)"
+	echo "-glx/-unconfig  Unconfigure server for use with VirtualGL (GLX + EGL back ends)"
+	echo "+egl            Configure server for use with VirtualGL (EGL back end only)"
+	echo "-egl            Unconfigure server for use with VirtualGL (EGL back end only)"
 	echo "-s              Restrict 3D X server access to vglusers group [default]"
 	echo "+s              Open 3D X server access to all users of this machine"
 	echo "-f              Restrict framebuffer device access to vglusers group [default]"
@@ -376,12 +379,12 @@ unconfigdev()
 		fi
 		if [ -f /etc/udev/rules.d/99-virtualgl-dri.rules ]; then
 			echo ... Removing /etc/udev/rules.d/99-virtualgl-dri.rules to restore default
-			echo "    permissions for /dev/dri/card0 at next boot ..."
+			echo "    permissions for /dev/dri/card* and /dev/dri/renderD* at next boot ..."
 			rm -f /etc/udev/rules.d/99-virtualgl-dri.rules
 		fi
-		if [ -f /etc/X11/xorg.conf.d/99-virtualgl-dri ]; then
+		if [ "$BACKEND" = "glx" -a -f /etc/X11/xorg.conf.d/99-virtualgl-dri ]; then
 			echo ... Removing /etc/X11/xorg.conf.d/99-virtualgl-dri to restore default
-			echo "    permissions for /dev/dri/card0 ..."
+			echo "    permissions for /dev/dri/card* ..."
 			rm -f /etc/X11/xorg.conf.d/99-virtualgl-dri
 		fi
 	fi
@@ -454,10 +457,15 @@ configdev()
 				chmod 660 /dev/nvidia*
 				chown root:vglusers /dev/nvidia*
 			fi
-			if [ -e /dev/dri/card0 ]; then
-				echo ... Granting write permission to /dev/dri/card0 for vglusers group ...
-				chmod 660 /dev/dri/card0
-				chown root:vglusers /dev/dri/card0
+			if ls /dev/dri/card* >/dev/null 2>&1; then
+				echo ... Granting write permission to /dev/dri/card* for vglusers group ...
+				chmod 660 /dev/dri/card*
+				chown root:vglusers /dev/dri/card*
+			fi
+			if ls /dev/dri/renderD* >/dev/null 2>&1; then
+				echo ... Granting write permission to /dev/dri/renderD* for vglusers group ...
+				chmod 660 /dev/dri/renderD*
+				chown root:vglusers /dev/dri/renderD*
 			fi
 		else
 			if [ -e /dev/nvidia0 -o -e /dev/nvidiactl ]; then
@@ -465,25 +473,32 @@ configdev()
 				chmod 666 /dev/nvidia*
 				chown root:root /dev/nvidia*
 			fi
-			if [ -e /dev/dri/card0 ]; then
-				echo ... Granting write permission to /dev/dri/card0 for all users ...
-				chmod 666 /dev/dri/card0
-				chown root:root /dev/dri/card0
+			if ls /dev/dri/card* >/dev/null 2>&1; then
+				echo ... Granting write permission to /dev/dri/card* for all users ...
+				chmod 666 /dev/dri/card*
+				chown root:root /dev/dri/card*
+			fi
+			if ls /dev/dri/renderD* >/dev/null 2>&1; then
+				echo ... Granting write permission to /dev/dri/renderD* for all users ...
+				chmod 666 /dev/dri/renderD*
+				chown root:root /dev/dri/renderD*
 			fi
 		fi
 		if [ -d /etc/udev/rules.d ]; then
 			if [ "$FBDEVVGLUSERSONLY" = "1" ]; then
-				echo "KERNEL==\"card[0-9]\", MODE=\"0660\", OWNER=\"root\", GROUP=\"vglusers\"" >/etc/udev/rules.d/99-virtualgl-dri.rules
+				echo "KERNEL==\"card*|renderD*\", MODE=\"0660\", OWNER=\"root\", GROUP=\"vglusers\"" >/etc/udev/rules.d/99-virtualgl-dri.rules
 			else
-				echo "KERNEL==\"card[0-9]\", MODE=\"0666\", OWNER=\"root\", GROUP=\"root\"" >/etc/udev/rules.d/99-virtualgl-dri.rules
+				echo "KERNEL==\"card*|renderD*\", MODE=\"0666\", OWNER=\"root\", GROUP=\"root\"" >/etc/udev/rules.d/99-virtualgl-dri.rules
 			fi
 		fi
-		if [ -d /etc/X11/xorg.conf.d ]; then
-			touch /etc/X11/xorg.conf.d/99-virtualgl-dri
-			setdripermissions /etc/X11/xorg.conf.d/99-virtualgl-dri
+		if [ "$BACKEND" = "glx" ]; then
+			if [ -d /etc/X11/xorg.conf.d ]; then
+				touch /etc/X11/xorg.conf.d/99-virtualgl-dri
+				setdripermissions /etc/X11/xorg.conf.d/99-virtualgl-dri
+			fi
+			setdripermissions /etc/X11/xorg.conf backup
+			setdripermissions /etc/X11/XF86Config backup
 		fi
-		setdripermissions /etc/X11/xorg.conf backup
-		setdripermissions /etc/X11/XF86Config backup
 	fi
 }
 
@@ -734,6 +749,29 @@ EOF
 		echo new device permission settings to become effective.
 	fi
 	echo
+}
+
+configegl()
+{
+	if [ $UNATTENDED = 0 ]; then
+		ynprompt "Restrict framebuffer device access to vglusers group (recommended)?"
+		if [ $? = 1 ]; then
+			VGLUSERSONLY=1; FBDEVVGLUSERSONLY=1;
+		else
+			VGLUSERSONLY=0; FBDEVVGLUSERSONLY=0;
+		fi
+	fi
+
+	if [ "$VGLUSERSONLY" = "1" ]; then
+		echo ... Creating vglusers group ...
+		if [ ! "$GID" = "" ]; then
+			$GROUPADD -g $GID vglusers || echo "Could not add vglusers group (probably because it already exists.)"
+		else
+			$GROUPADD vglusers || echo "Could not add vglusers group (probably because it already exists.)"
+		fi
+	fi
+
+	configdev
 }
 
 configglx()
@@ -1017,6 +1055,8 @@ while [ $# -gt 0 ]; do
 		-glx) CONFIG_VGL="unconfigglx"; UNATTENDED=1 ;;
 		-config) CONFIG_VGL="configglx"; UNATTENDED=1 ;;
 		-unconfig) CONFIG_VGL="unconfigglx"; UNATTENDED=1 ;;
+		+egl) BACKEND=egl; CONFIG_VGL="configegl"; UNATTENDED=1 ;;
+		-egl) BACKEND=egl; CONFIG_VGL="unconfigdev"; UNATTENDED=1 ;;
 		*) usage 0
 	esac
 	shift
@@ -1038,8 +1078,10 @@ if [ $UNATTENDED = 0 ]; then
 	while [ 1 ]
 	do
 		echo
-		echo "1) Configure server for use with VirtualGL"
-		echo "2) Unconfigure server for use with VirtualGL"
+		echo "1) Configure server for use with VirtualGL (GLX + EGL back ends)"
+		echo "2) Unconfigure server for use with VirtualGL (GLX + EGL back ends)"
+		echo "3) Configure server for use with VirtualGL (EGL back end only)"
+		echo "4) Unconfigure server for use with VirtualGL (EGL back end only)"
 		echo "X) Exit"
 		echo
 		echo Choose:
@@ -1049,6 +1091,10 @@ if [ $UNATTENDED = 0 ]; then
 		1) configglx
 			;;
 		2) unconfigglx
+			;;
+		3) BACKEND=egl; configegl
+			;;
+		4) BACKEND=egl; unconfigdev
 			;;
 		X) break
 			;;
