Properly handle multi-level SSh tunnel Use -Y only on SSh versions >= 3.8
git-svn-id: svn+ssh://svn.code.sf.net/p/virtualgl/code/trunk@1776 799e4f7b-5fd2-41f6-823c-2ecc41bc7f0b

diff --git a/rr/vglconnect b/rr/vglconnect
--- a/rr/vglconnect
+++ b/rr/vglconnect
@@ -42,35 +42,48 @@ if [ "$DISPLAY" = "" ]; then
 	exit -1
 fi
 
+SSHARG='-X'
+SSHVER=`ssh -V 2>&1 | sed 's/.*[_]//g' | sed 's/[, ].*//g'`
+if [ $? -ne 0 -o "$SSHVER" = "" ]; then
+	echo "[VGL] ERROR: Could not find ssh in your PATH."
+	exit -1
+fi
+case "$SSHVER" in
+3.8*) SSHARG='-Y' ;;
+3.9*) SSHARG='-Y' ;;
+4*) SSHARG='-Y' ;;
+5*) SSHARG='-Y' ;;
+esac
+
 LOGDIR=$HOME/.vgl
 if [ ! -d $LOGDIR ]; then mkdir $LOGDIR; fi
 LOGFILE=$LOGDIR/vglconnect-`hostname`-$DISPLAY.log
 
 VGLARGS="-l "$LOGFILE" -d "$DISPLAY" -detach"
 if [ "$FORCE" = "1" ]; then VGLARGS=$VGLARGS" -force"; fi
-VGLCONNECT=`which $0`
-VGLCLIENT=`dirname $VGLCONNECT`/vglclient
-if [ ! -x $VGLCLIENT ]; then
-	if [ -x /opt/VirtualGL/bin/vglclient ]; then
-		VGLCLIENT=/opt/VirtualGL/bin/vglclient
-	else
-		if [ -x /opt/SUNWvgl/bin/vglclient ]; then
-			VGLCLIENT=/opt/SUNWvgl/bin/vglclient
+if [ ! "$VGL_PORT" = "" -a "$__VGL_SSHTUNNEL" = "1" ]; then
+	PORT=$VGL_PORT
+else
+	VGLCONNECT=`which $0`
+	VGLCLIENT=`dirname $VGLCONNECT`/vglclient
+	if [ ! -x $VGLCLIENT ]; then
+		if [ -x /opt/VirtualGL/bin/vglclient ]; then
+			VGLCLIENT=/opt/VirtualGL/bin/vglclient
 		else
-			VGLCLIENT=vglclient
+			if [ -x /opt/SUNWvgl/bin/vglclient ]; then
+				VGLCLIENT=/opt/SUNWvgl/bin/vglclient
+			else
+				VGLCLIENT=vglclient
+			fi
 		fi
 	fi
+	PORT=`$VGLCLIENT $VGLARGS`
+	if [ $? -ne 0 -o "$PORT" = "" ]; then
+		echo "[VGL] ERROR: vglclient failed to start.  Check $LOGFILE for errors."
+		exit -1
+	fi
+	echo
 fi
-PORT=`$VGLCLIENT $VGLARGS || echo -1`
-if [ "$PORT" = "-1" ]; then
-	echo "[VGL] ERROR: vglclient failed to start."
-	exit -1
-fi
-if [ "$PORT" = "" ]; then
-	echo "[VGL] ERROR: vglclient failed to start.  Check $LOGFILE for errors."
-	exit -1
-fi
-echo
 
 if [ $VGLTUNNEL = 1 ]; then
 	REMOTEPORT=`ssh ${1+"$@"} '/opt/VirtualGL/bin/nettest -findport && /opt/VirtualGL/bin/vgllogin -check'`
@@ -79,12 +92,12 @@ if [ $VGLTUNNEL = 1 ]; then
 		echo "[VGL]    installed."
 		exit -1
 	fi
-	ssh -t -Y -R$REMOTEPORT:localhost:$PORT ${1+"$@"} '/opt/VirtualGL/bin/vgllogin -s '$REMOTEPORT
+	ssh -t $SSHARG -R$REMOTEPORT:localhost:$PORT ${1+"$@"} '/opt/VirtualGL/bin/vgllogin -s '$REMOTEPORT
 	exit 0
 fi
 
 if [ $X11TUNNEL = 1 ]; then
-	ssh -Y ${1+"$@"}
+	ssh $SSHARG ${1+"$@"}
 	exit 0
 fi
 
